source'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

inhibit_all_warnings!
use_modular_headers!
use_frameworks!

# 共享
def share_pods
  pod 'Localize-Swift', '~> 3.2.0'
  pod 'HandyJSON', '5.0.2'
  #pod 'Firebase', '~> 10.25.0'
  #pod 'FirebaseCrashlytics', '~> 10.25.0'
  #pod 'FirebaseRemoteConfig', '~> 10.25.0'
  pod 'SnapKit', '~>5.7.1'
  pod 'Masonry'
  pod 'WCDB.swift', '~> 2.0.2.5'
  pod 'WCDBOptimizedSQLCipher', '1.4.1'
  pod 'Alamofire'
  pod 'SSZipArchive'
  pod 'YYImage', '~>1.0.4'
  pod 'YYImage/WebP', '~>1.0.4'
  pod 'libwebp', '~> 1.2.1'
end

target 'PaiZhaoShiHua' do
  share_pods
   #swift

 #pod 'ESTabBarController-swift', '~> 2.8.0'
 #pod 'IQKeyboardManagerSwift', '~> 6.5.10'
 #pod 'ObjectMapper', '~> 4.2.0'
 #pod 'JXSegmentedView', '~> 1.2.7'
 #pod 'Kingfisher', '~> 6.3.1'
 #pod 'ZCycleView', '~> 1.0.3'
# pod 'ZLPhotoBrowser', '~> 4.3.1'
#pod 'SVProgressHUD'

 #pod 'ReachabilitySwift', '~> 5.0.0'
 #pod 'Google-Mobile-Ads-SDK', '~> 9.5.0'
# pod 'KingfisherWebP', '~> 1.3.0'
# pod 'WCDBSwift', '~> 1.0.2'
 pod 'DropDown', '~> 2.3.13'
# pod 'JTAppleCalendar', '~>8.0.3'
# pod 'Charts'
 pod 'Toast-Swift', '~> 5.0.1'
 pod 'BEMCheckBox', '~> 1.4.1'
 pod 'SnapKitExtend', '~> 1.1.0'
# #OC
# pod 'MBProgressHUD', '~> 1.2.0'
pod 'SideMenu', '~> 6.5.0'
#pod 'PanModal'
pod 'HWPanModal', '~> 0.8.9'
#pod 'FSCalendar', '~> 2.8.4'
#pod 'TagListView', '~> 1.0'
pod 'SwiftSVG', '~> 2.3.2'
#pod 'PNChart'
# pod 'PNChart', :path => '~/Desktop/工作/TODO/PNChart-master'
 #pod 'TYCyclePagerView', '~> 1.2.0'
 pod 'YYModel', '~> 1.0.4'
 pod 'YYText', '~> 1.0.7'

 pod 'lottie-ios', '~> 2.5.3'
 #pod 'Google-Mobile-Ads-SDK'
# pod 'GoogleUserMessagingPlatform'
 
# pod 'SwiftEntryKit', '2.0.0'
pod 'AliyunOSSiOS', '2.10.10'
pod 'SVProgressHUD', '2.3.1'
# Podfile
pod 'SwiftyMarkdown'
#pod 'Kingfisher'  # 最新稳定版

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
#      if !deployment_target.nil? && !deployment_target.empty? && deployment_target.to_f < 11.0
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#      end
#    end
#  end
#end
